### ISSUE TITLE
Menstrual Cycle Survey Trigger changes

### ISSUE THREAD

**Issue by cusackjm** [episphere/connect#1017]
- delay launch to 5 days @ DevOps
- Trigger survey off 1st email notification @ DevOps
- add 5th reminder at 35 days @HanaShiho 

Menstrual Cycle Survey Requirements: https://nih.app.box.com/file/1504923433431

**Comment by sonyekere** [comment]
Hi, Will this be going into the July release?

**Comment by jhflorey** [comment]
After looking through this problem I realized what needs to be done is

- Update survey trigger from “immediately” to “5 days” post biospecimens survey submission
- Turn of the 1st email notification (5 days)
- Follow-up reminders will be 10 days, 15 days, 20, 35, 45 days after the date of submission of the biospecimen quex.
- When do we close surver (after 45 days)?

Please correct me if i was wrong.

**Comment by brotzmanmj** [comment]
@jhflorey not exactly, we need to review internally and better explain requirements. We will get back to you shortly.

**Comment by rohanjay10** [comment]
If we are making these changes looks like the MOOP may have to be updated as well. Specifically when the survey is available, the number of follow up reminder emails, and when they are sent. As well as any new information we are adding.

![Screenshot 2024-06-11 at 2 51 38 PM](https://github.com/episphere/connect/assets/167465793/2dd50645-ab3b-41cb-8817-c22c8e18a9fa)
[MOOP](https://nih.app.box.com/file/1336123139436?s=s2pv5hb66uw1ab42gsdiyan3txggn0ja)

**Comment by brotzmanmj** [comment]
Requirements document has been updated. 

Next step is that we need to discuss consolidating the existing email notifications and fixing the conditionality to include the derived variable.  @HanaShiho will set up a meeting.

**Comment by brotzmanmj** [comment]
Deanna and Hana and I reviewed the notification specs this morning and found that they cannot be consolidated and they do already include the derived variable. 

I updated the requirements document again. We are ready to discuss at the meeting Hana set up for next week.

**Comment by rohanjay10** [comment]
@jhflorey 
Based on the updated requirements document:

- MC Survey trigger is the 1st email notification that is sent 5 days after the biospec survey submission.
- Follow up reminders will be sent 10, 15, 20, and 35 days (2nd, 3rd, 4th, 5th notification respectively) after the date of submission of the biospec survey 
- MC Survey will be closed if it has been more than 45 days since the Biospec survey submission and the MC survey is not submitted yet.

All, let me know if the above needs to be corrected.

Hana has set up a meeting next week for the team to discuss this and other requirements further.

**Comment by rohanjay10** [comment]
4/17/24 Call Summary and Next Steps

> * MC Survey trigger is the 1st email notification that is sent 5 days after the biospec survey submission.
1.  @jhflorey to find out from Tony how exactly the current MC Survey is triggered through the derived variable. 
Currently MC Survey is triggered through a derived variable upon "immediate" submission of bio specimen survey. For the future state, we need to derive the variable as it is done currently, with no changes, and **then trigger the MC Survey upon the 1st email notification sent after 5 days on biopic. survey submission.** 

2. @jhflorey to check with Tony about what needs to be done to maintain the same message ids between tiers(PROD > DEV). 
The message IDS that exist on Prod, and do not exist in Dev(only in draft) should be the same message ids in Dev. We need to check on what needs to be done to maintain the same message ids in Dev. 
2a) Once @jhflorey checks this, @HanaShiho will update Exclusion criteria. 

> * Follow up reminders will be sent 10, 15, 20, and 35 days (2nd, 3rd, 4th, 5th notification respectively) after the date of submission of the biospec survey
3. @HanaShiho to add reminder after 35 days. 

4. Once we have the above information and @jhflorey is ready we'll be able to test with the conditions and push it through all the tiers. 

@brotzmanmj @HanaShiho Please feel free to add on or correct any of the above.

**Comment by brotzmanmj** [comment]
Thank you for this excellent summary. Just adding that for the future state, the MC Survey will trigger off two '1st email notifications' because one 1st notification goes to people who did research collections and one 1st notification goes to people who gave clinical collections.

**Comment by anthonypetersen** [comment]
@brotzmanmj @jhflorey @rohanjay10 here is what I think should be done regarding this update to trigger the survey, let me know your thoughts:

* Change the default value of the Menstrual Cycle Survey status from 972455046 (Not Started) to 789467219 (Not Yet Eligible)
  * This would also require mass participant update in prod upon go-live of changes
* Keep derived variable code unchanged for 289750687 (Menstrual Survey Eligible)
* Add code to our notification logic that will change Menstrual Cycle Survey status to 972455046 (Not Started) upon first email notification (or sms?) 
  * This is something we are already doing for the PROMIS survey
* PWA code will need to be updated to reference Menstrual Cycle Survey status instead of Menstrual Cycle Survey eligibility to determine if we will display the survey on the To-Do List
  * We will keep the logic in place that only displays the survey for 45 days after the participant's biospecimen survey was completed (clinical or research)

**Comment by brotzmanmj** [comment]
@anthonypetersen 
I agree with your approach. A few questions/clarifications:
"Change the default value of the 459098666 (Menstrual Survey Status) from 972455046 (Not Started) to 789467219 (Not Yet Eligible). This would also require mass participant update in prod upon go-live of changes" Would this negatively impact anyone for whom the MC Survey has already been triggered?

"Add code to our notification logic that will change 459098666 (Menstrual Survey Status) to 972455046 (Not Started) upon first email notification (or sms?)" I think it should be first email notification but note there are two email notifications (one for people who did research collections and one for people who did clinical collections) so we need to tie it to both.

Also update the SMDB Participant Summary page to display the MC Survey status according to reflect 459098666 (Menstrual Survey Status) and show up for everyone, which is different than what it does now.

Will out email/SMS notification logic need to change at all? Currently the message sends if someone is 289750687 (Menstrual Survey Eligible) = 'yes' and stops when 459098666 (Menstrual Survey Status) = 'submitted'

**Comment by brotzmanmj** [comment]
@anthonypetersen One more thing because this just came up... what happens if someone completes a clinical sample and a research sample as happened at HFH just now. The person submitted both the clinical biospec survey and then the research biospec survey. Does the variable 289750687 (Menstrual Survey Eligible) derive just once or would it possible get 're-derived'/changed/overwritten in this circumstance?

**Comment by brotzmanmj** [comment]
1. We could do a mass update that says something like "if the participant hasn't gotten the first email and hasn't started the survey, update their status to Not Yet Eligible" - that way the system can update them to Not Yet Started when appropriate.  [Sounds good]
2. We can easily listen for the first instance of either email. Do we need to listen for SMS messages as well? [No, email will be more inclusive so just email is fine]
3. Do you just mean update it so that it shows Not Yet Eligible / Not Yet Started as appropriate? [Yes]
4. No, we should be able to keep all of that intact. [Great]
5. We only try to derive 289750687 (Menstrual Survey Eligible) as long as it is not equal to Yes. Once they become eligible, we no longer try to re-derive it. [This should also be fine]

I think we are good to go forward as suggested! Thanks.

**Comment by anthonypetersen** [comment]
@jhflorey please see last few comments

**Comment by we-ai** [comment]
Below are my comments on this issue. Please correct me if I'm wrong.
- Displaying the delayed Menstrual Cycle Survey can be achieved without mass updating participants data. To display menstrual cycle survey at day 5 after biospecimen survey, when loading PWAs page we can check whether 5 days have passed after biospecimen survey. 
- We have 289750687 (Menstrual Survey Eligible) and may not need 789467219 (Not yet eligible) as a default value for 459098666 (Menstrual cycle survey completion). 

The notification system is for sending out emails and SMS messages, and we're trying to boost to 10x of current capacity so that it can efficiently send out 200,000 emails and 200,000 SMS messages during a scheduled run. This is why I suggest avoid adding unnecessary data update logics inside notification handling, because they slow down notification handling. The data updates are better done outside notification handling.

**Comment by anthonypetersen** [comment]
@brotzmanmj is it a hard requirement that the survey needs to appear at the same time the email goes out? would it be acceptable to have the survey become available on the day the participant is set to receive the first email?

**Comment by brotzmanmj** [comment]
@anthonypetersen I think that would require a quick discussion. Are you saying you don't want to condition the survey trigger on the notification?

**Comment by anthonypetersen** [comment]
@brotzmanmj with Warren attempting to make improvements to our notification code to allow for further scaling as the study grows, he has concerns about putting additional code like what would be required. See one of his comments on the PR: https://github.com/episphere/connectFaas/pull/616#issuecomment-2214159828

@we-ai please comment if you have any other thoughts

**Comment by brotzmanmj** [comment]
@anthonypetersen and @we-ai  Going back to the original premise, the first instance where we decided to link a survey trigger to a notification was for PROMIS/QOL survey and that was because there was nothing else to trigger it on. In other words, we did not have the ability to condition the trigger on 'if the person was verified after 12/1/2023 and had not refused future surveys and had not withdrawn from Connect, trigger this survey to appear on their To Do list 90 days after verification.' Instead we conditioned the email on the above and then set the survey trigger based on the email notification being sent (or attempted to send).

Is the menstrual cycle survey different in some fundamental way such that we can condition is to appear 5 days after the biospecimen survey is submitted if they are eligible for it, not withdrawn, and not refused?

**Comment by brotzmanmj** [comment]
@anthonypetersen In that case, we could do as Warren suggested:

If we want to match the time of survey reminder and survey, assuming notifications are sent out without issues, we can open the survey at 3pm on day 5 by checking participant data.

We just need to match conditions.

**Comment by anthonypetersen** [comment]
@brotzmanmj we are discussing technical options internally and will report back what we decided and can discuss what implications there might be from an operations pov

**Comment by we-ai** [comment]
> @anthonypetersen and @we-ai Going back to the original premise, the first instance where we decided to link a survey trigger to a notification was for PROMIS/QOL survey and that was because there was nothing else to trigger it on. In other words, we did not have the ability to condition the trigger on 'if the person was verified after 12/1/2023 and had not refused future surveys and had not withdrawn from Connect, trigger this survey to appear on their To Do list 90 days after verification.' Instead we conditioned the email on the above and then set the survey trigger based on the email notification being sent (or attempted to send).
> 

We should be able to implement the conditions in PWA without using email notification to update data.

**Comment by anthonypetersen** [comment]
Discussion notes w/ @brotzmanmj - 
* survey will become available on dashboard 120 hours (5 days) after completion of bio survey if participant is menstrual survey eligible
* first email notification will go out at 3PM notification run once it has been 120 hours (5 days) since bio survey completion
* NOTE: there will likely be a small window when survey is available for participant to complete prior to receiving first notification, Operations is aware of this and is good with it

**Comment by HanaShiho** [comment]
This is ready for stage (thank you Erin for testing the survey triggers in dev!)
