### ISSUE TITLE
Participation Status (d_912301837) Not Correctly Set for Participant

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#1031]
The QC report this week showed that Connect ID 7927615072 has withdrawn consent, but their participation status (d_912301837) is “no refusal” (208325815) instead of “withdrew consent" (854021266). 

This participant has revoked HIPAA, withdrawn consent, is not deceased, and has not requested data destruction, so their participation status should be "withdrew consent".  

@sonyekere could you please assign this to someone to look into the derivation?

**Comment by sonyekere** [comment]
Hi @mnataraj92,  We'll aim to assign this shortly.

**Comment by brotzmanmj** [comment]
Hi @sonyekere  when you're back I wonder if you can assign this to someone for July. It's concerning that the Participation Status does not appear to have derived correctly for this person.

**Comment by sonyekere** [comment]
Hi @mnataraj92 and @brotzmanmj Alerting that DevOps met and would like to propose that since this issue is not causing major breaks outside of this single participant, it might be better prioritized for a later release (August/September). There are quite a few enhancements and cleanups that DevOps will be working through, and the bandwidth is needed for July and August

**Comment by sonyekere** [comment]
Per internal 'mid week planning meeting' - this no longer seems to be an issue and can be marked done.
