### ISSUE TITLE
Program Spanish html for the Anniversary email

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1046]
Placeholder, pending HTML from Operations, once received DevOps to program and test the Spanish Anniversary email.

**Comment by depietrodeanna** [comment]
Html code here: https://nih.app.box.com/file/1579535236330 please coordinate with @HanaShiho and me for testing assistance as well.

**Comment by jhflorey** [comment]
@depietrodeanna @HanaShiho Please try with this content https://gist.github.com/jhflorey/1e3115d4be7f5f11864ac0142116bdc0

**Comment by HanaShiho** [comment]
@jhflorey Hi, thank you for the updated content! I tested it in dev and have two comments. See the screenshot below: **"YEAR"** on the yellow ribbon/banner should also be translated; it should be **"año."** Otherwise, it looks good! 

Secondly, when I clicked 'Ver en navegador' in the upper right-hand corner, the content in view in browser mode was rendered in English instead of Spanish. 
![image](https://github.com/user-attachments/assets/ac56a479-df75-42fb-8289-90733abde229)

**Comment by jhflorey** [comment]
@HanaShiho  `"YEAR" on the yellow ribbon/banner should also be translated; it should be "AÑO"` => It's image (https://raw.githubusercontent.com/episphere/dashboard/dev/siteManagerDashboard/assets/images/anniversary-graphic.png). Please provide the image for Spanish.

**Comment by depietrodeanna** [comment]
@jhflorey graphic here:
![One-Year-Annv-ES](https://github.com/user-attachments/assets/980ea974-c811-42c3-8e01-507d211196f4)

**Comment by jhflorey** [comment]
Hi @depietrodeanna  @HanaShiho, the Spanish anniversary is already in dev. Please check the UI here https://episphere.github.io/dashboard/newsletter/anniversary-spanish

@HanaShiho The content is https://gist.github.com/jhflorey/1e3115d4be7f5f11864ac0142116bdc0 please try it.

**Comment by HanaShiho** [comment]
tested in dev, ready for stage 
![image](https://github.com/user-attachments/assets/6caf4350-02f7-40f0-a737-cf70c19c6476)

**Comment by HanaShiho** [comment]
Ready for prod
