### ISSUE TITLE
Home collections - prevent two baseline kits assigned to same participant (Biospecimen)

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connect#1109]
On Friday August 30, two baseline home mouthwash kits intended for two distinct participants both got assigned to the same participant. It is unclear how this happened in the dashboard, but it was not human error on the part of the BPTL staff. When Tony, Joe, and Michelle looked at the underlying data in the Participants table to investigate the issue, we found the nested variables at the 4th level for the baseline home mouthwash kit were repeated with two different kits linked.

We need to prevent this from occurring, as part of greater coding review/optimization.

We also need to view this in relation to our upcoming work to allow for two replacement kits to be sent to a participant.

**Comment by sonyekere** [comment]
Time to home mouthwash collection optimization effort

**Comment by amber-emmes** [comment]
This should now be in dev and ready to test. Please review the process thoroughly and let Dev-Ops know if you need anyone to manually review any of the data in Firestore to ensure appropriate flags are set.

**Comment by amber-emmes** [comment]
This is now in stage and ready for review.

**Comment by erincschwartz** [comment]
Tested in Dev, ready for Stage. 

- Attempted to Assign Kit and stopped short of clicking 'save' then refreshed the screen---kit was still in Pending status (expected behavior)
- Assigned kit fully, then refreshed Assign Kit screen and manually entered participant information and attempted to assign a new kit. The system would not allow: 
 ![Image](https://github.com/user-attachments/assets/80fd04ed-81d7-4cbd-91b0-e5fa8e9d6d84)
- Seems that with current programming, the system should prevent future cases where a single participant is assigned two home mouthwash kits.

**Comment by erincschwartz** [comment]
Tested in Stage, **ready for Prod**

- Attempted to Assign Kit and stopped short of clicking 'save' then refreshed the screen---kit was still in Pending status (expected behavior)

- Assigned kit fully, then refreshed Assign Kit screen and manually entered participant information and attempted to assign a new kit. The system would not allow:
-![Image](https://github.com/user-attachments/assets/02c29276-2e4a-4510-9113-3305733914d2)
