### ISSUE TITLE
NORC Survey Reset Tool 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#1130]
DevOps will need to reset the correct survey variables and ensure that It is active and working as expected. 

Placeholder for additional requirements. @mnataraj92 please add on to the requirements if needed.

**Comment by mnataraj92** [comment]
Discussed this with @brotzmanmj yesterday. NORC is to send the tool to us for approval. We need to make sure that it doesn't mess up any dependencies, etc. It should wipe the survey data that we have for the particular survey, in addition to resetting the survey status flags and the time started/time completed flags. 

Note that some of the survey status flags (like the PROMIS survey flag and the Connect Experience Survey flag) are not default variables, so the reset of the flag would set it to null for those instead of 'not started'. 
	
Also @brotzmanmj would this also incorporate resetting the Github/Survey version variables? 

For the SSN survey resets, there are a few additional variables to consider since we have flags & timestamps for both full and partial SSN in addition to deleting the actual full/partial SSN entered in the survey. There is also the Time Acct - SSN variable (d_463625040) which I don't think is being used. 

We also want to decide on where on the dashboard this should decide. 

We also need to take into account the rules around the variables that this impacts. For example, if there is data for Modules 2-4, then Module 1 data should not be deleted. The menstrual cycle survey is also dependent on the biospecimen surveys, so we have to be cautious about deleting menstrual cycle survey data if biospecimen survey data is filled out. We also need to think about derived variables that are dependent on the survey status flags. @JoeArmani when you get a chance, could you please provide the list of derived variables?

**Comment by mnataraj92** [comment]
Thanks Michelle! I'm planning on reaching out to them later today to go over the October release items they'll be involved with.

**Comment by brotzmanmj** [comment]
Thanks. Also Madhuri, please create a table on Box and link it here. List each module, what changes to each variable would need to be changed for each one, by Concept ID, just like you would do if you were making the request on the prod manual change log. And what additional rules there are for a specific module, if any. e.g. Module 1 cannot be reset if the participant has started modules, 2, 3, or 4. 

Tony usually does the prod manual changes for survey resets, so perhaps he can check if anything is missing from your list to guide the programmer on this, and also answer questions about survey version and language flag.

Thanks

**Comment by JoeArmani** [comment]
@mnataraj92 Here's the Box doc with derived variables and survey-related variables https://app.box.com/s/kc8ugxvosd9h5z3glinufwr0thvwlpgi

**Comment by anthonypetersen** [comment]
@mnataraj92 for all surveys, we don't need to delete GitHub versions or survey language. Those are captured within the survey document and will be deleted when the document is deleted

**Comment by anthonypetersen** [comment]
@mnataraj92 for the SSN Survey...

* SSN 9 digits / SSN 4 digits is deleted when the SSN document is deleted
* 463625040 doesn't appear to be something that's being captured

**Comment by mnataraj92** [comment]
@anthonypetersen thank you!! i will make a note of these in the spreadsheet.

Does everything else look okay to you?

**Comment by brotzmanmj** [comment]
Amelia and I were just discussing and we're going to need some rules around survey deletion when there are dependencies involved... primarily:
-Can't delete Module 1 if Module 2, 3 or 4 have been started or submitted (since they are dependent on data from Module 1)
-Can't delete BUM or BU (biospecimen surveys) if person is eligible for Menstrual Cycle survey since the latter is dependent on data from BUM and BU

Are there any other dependencies that we should be concerned about?

**Comment by anthonypetersen** [comment]
> @anthonypetersen thank you!! i will make a note of these in the spreadsheet.
> 
> Does everything else look okay to you?

yes

**Comment by anthonypetersen** [comment]
@brotzmanmj where my head starts to go is any derived variables that rely on survey completion - a few examples...

* incentive eligibility
* all baseline surveys complete (100767870)
* you already mentioned one in menstrual cycle survey eligibility (289750687)

**Comment by brotzmanmj** [comment]
@anthonypetersen good point...

We would need to know more about when/how these and any others get derived and what the impact might be.
- baseline incentive eligibility - if they are already incentive eligible we would not want them to change to 'not eligible', they should stay eligible. Would the variable ever attempt o re-derive from 'yes' to 'no'? 

-'all baseline surveys complete' (100767870) - under what circumstances does this derive? If it was ever 'yes' would it change back to 'no' if the survey status for one or more of the four modules changed?

-menstrual cycle survey eligibility (289750687) - Did we stop using this variable and deprecate it in a recent release when we changed the way the MC Survey triggers?

**Comment by anthonypetersen** [comment]
@brotzmanmj 

1. If they were ever set to Incentive Eligible, the derivation code as it stands shouldn't revert them back to No for any reason
2. All Baseline Surveys Complete derives at the same time other derived variables are calculated (survey submission, biospecimen submission, Update Participant Data API call, etc.) Once set to Yes, it would not get set to No in the current derivation code
3. The variable is still used in code as it's part of the calculation for if someone should see the survey

**Comment by rohanjay10** [comment]
Hi all, [here is the updated draft](https://nih.app.box.com/file/1685086939110) of the Survey Reset tool technical requirements, compiling the various information/links. Please feel free to make changes/comments.

**Comment by rohanjay10** [comment]
Here are the dependencies for preferred 'Select Tool' option for Survey Reset tool discussed in today's call:
- NORC would only be able to submit 1 correction at a time. For example, in the future once multiple surveys get added(initially SSN survey) only 1 survey would be able to be submitted at a time(as it would be a prod level change)
- SSN Survey can be reset if its status is 'started' or 'submitted', but for other surveys they would only be allowed to be reset if they were in the 'started' status
-Madhuri to provide SSN Concept IDS to Gene
- Verification Status/Duplicate Type/ Recruitment type should work how we currently do it in the SMDB in prod 
- Nothing to note for Prod Manual Changes as both tools are straightforward 

Feel free to add on

**Comment by brotzmanmj** [comment]
@sonyekere  can you add a link to updated UI to this issue? thanks

**Comment by brotzmanmj** [comment]
Hi, Can you delete the slides on the Single Page solution since we've decided to go with the Separate Pages solution?

**Comment by Gbarra9** [comment]
Hi @brotzmanmj,  I deleted the single page mockups. I left the old data corrections tool as a reference (Slide 2), let me know if you also want this removed. Changes and adjustments were made and I left comments in Box. Refer to Incentive Eligibility Slides (Slides 8 & 10). Let me know if wording or other UI changes are needed. Thank you.

PowerPoint in Box: https://nih.app.box.com/file/1679759783643?s=ry5idww61bdmlo2dg28upiedtb8irwsm

**Comment by sonyekere** [comment]
**Noting here that the December release of the survey reset tool will only include the SSN survey (11/5)**

**Comment by rohanjay10** [comment]
Adding a requirement that: When the Survey Reset tool resets a SSN survey the participant's SSN document in Firestore should be deleted - based on Gene checking with Tony. Adding this to the technical requirements document linked above.
This originally came up in a call to review the tool + going through test scenarios.

**Comment by Gbarra9** [comment]
> @Gbarra9 here's the suggested wording and layout updates for both of the NORC tools: https://nih.app.box.com/file/1716762391027. Posted to Box for ease of copying and pasting.

@robertsamm Thanks for the document in Box and for the ease of copying/pasting. I'll message if I have any questions.

**Comment by rohanjay10** [comment]
This has been tested in dev and is ready for stage

**Comment by rohanjay10** [comment]
This has been tested in stage and is ready for prod
