### ISSUE TITLE
KP Sites End of Year Thank you Letter 

### ISSUE THREAD

**Issue by HanaShiho** [episphere/connect#1172]
We plan to send out a year-end thank-you letter to the KP sites. The final content can be found [HERE](https://nih.app.box.com/file/1706405296126?s=9dg7kx21zxlgqmt2laoywmgyla3ggfkl). The letter format contains word texts and [images](https://nih.app.box.com/folder/252401214887?s=e6h507nkfe4189n917vopzui2g3ledpp). @jhflorey, can you please look at the linked doc and let us know what we'd need from the site to render the image in SMDB? Does it need to be in a specific format? If so, can you let me know what specifications you need?

**Comment by depietrodeanna** [comment]
Jessica, for testing ease, the html code for KPCO test spec in dev is below in English. Subject line: From the Connect team at KP: Thank you, KPCO members!

Dear <firstName>,<br/><br/><strong>Celebrating our efforts to help uncover the causes of cancer.</strong><br/><br/><img src="https://raw.githubusercontent.com/episphere/studyManagerDashboard/refs/heads/dev/assets/images/kp-site/kpco-image-option-1.jpg?raw=true"/><br/><br/>As 2024 comes to a close, researchers with the Connect for Cancer Prevention Study want to acknowledge and celebrate all that <u>you</u> have helped us achieve this year. We’re doing it — in fact, we can only do it — thanks to our Kaiser Permanente members and staff.<br/><br/>The Connect for Cancer Prevention Study, known as Connect, is an extensive, federally funded study led by the National Cancer Institute (NCI), the largest funder of cancer research in the world. With an aim to learn more about what causes cancer and how it can be prevented, NCI is partnering with several healthcare organizations across the U.S., including Kaiser Permanente in Colorado, Oregon, SW Washington, Georgia, and Hawaii.<br/><br/>In 2024, <u>with your help,</u>  we have achieved the following milestones since we began recruitment:<br/><ul><li><strong> 7,839 </strong>participants joined Connect at KPCO</li><li><strong>5,581 </strong>participants completed their first Connect survey (71% of enrolled participants)</li><li><strong>5,578 </strong>participants donated their first biological samples (71% of enrolled participants)</li><li><strong> 22,672 </strong> participants joined Connect at all KP sites</ul></li>The Connect team at KPCO would like to thank you -- our dedicated KPCO members and staff who have contributed to the success of the study this year! We are beyond grateful for your support.<br/><br/>Consider sharing the [Connect website] (https://www.cancer.gov/connect-prevention-study/) with someone you know who may be interested in learning more about joining the study. We invite people from all backgrounds to join Connect, so the health discoveries can benefit everyone. We look forward to continuing to connect with you in 2025! Thank you for partnering with us. We are so grateful for you, and all you are doing to prevent cancer. Connect today to help prevent cancer tomorrow.<br/><br/>Sincerely,<br/>The Connect team at KPCO<br/>![Connect logo](https://raw.githubusercontent.com/episphere/connectApp/master/images/new_logo.png =150x40)<br/><br/>*To protect your information, we follow federal privacy rules, including the [Privacy Act](https://www.justice.gov/opcl/overview-privacy-act-1974-2020-edition) and the [Common Rule](https://grants.nih.gov/grants/guide/notice-files/NOT-OD-19-050.html).<br/><br/>This message is private. If you have received it by mistake, please let us know by emailing [ConnectSupport@NORC.org](mailto:ConnectSupport@NORC.org), and please kindly delete the message. If you are not the right recipient, please do not share this message with anyone*. <br/>

**Comment by depietrodeanna** [comment]
Tested in Stage and approved to move to prod for one time send to all KP participants on 12/16
