### ISSUE TITLE
Consent

### ISSUE THREAD

**Issue by mbaldwinkpco** [episphere/connect#158]
Misspelled participant name when signing consent - not flagged.

**Comment by strennr** [comment]
A few observations about he consent screen/process:

1. When downloading the consent form, the next steps are unclear.  Should there be an option to upload a completed consent form or is the only option to consent electronically in the PWA app?

2. When downloading the consent form, the file is saved as "coonect_consent.pdf" instead of "connect_consent.pdf".

3. When opening the downloaded consent form, it appears to be a working copy (which may be expected at this point).

**Comment by hzhao392** [comment]
We dont have finalized consent PDF yet. The file name has been changed. The misspelled name is captured in https://github.com/episphere/connect/issues/152 Please let us know if this is a requirement

**Comment by brotzmanmj** [comment]
For 1, the download of the consent form is just for the participant. It should contain their signature and date (if they download after they sign) and they should also be able to download the form before signing if they just want to read it carefully. Hui, can we double-check and make sure this is working as intended?

There is no option to upload a signed consent; the only option is to consent electronically in the PWA.  If this is not clear, we need to provide better instructions on the consent page.
