### ISSUE TITLE
Make the participant dashboard easier to use

### ISSUE THREAD

**Issue by paulzakin** [episphere/connect#161]
UoC intends to have RAs use the dashboard to look at what information was submitted by the participant for manual verification. However, the dashboard, it the current state, is hard(ish) to use, because of the reliance on the numerical codes. Can you include an option to have all numerical codes coverted to "Plain English" labels, like address? Or, simply have that as the default. From a UX perspective, I don't really see the advantage offered by a "code first" approach!

![image](https://user-images.githubusercontent.com/19244099/95366178-b6cef600-0898-11eb-8e6c-2f9e1e413cef.PNG)

**Comment by brotzmanmj** [comment]
To add to this comment, the Study Managers are working on a mock up of their dashboard to better suit their needs. I'll ask them to include the 'user friendliness' of this aspect in their requirements. For sure we will need to display the variable labels throughout the dashboard rather than concept IDs.

**Comment by bhaumik55231** [comment]
Hi, @paulzakin @brotzmanmj It will be shown as labels instead of concepts, just haven't had a chance to work on it.

**Comment by paulzakin** [comment]
That works for me!

**Comment by Davinkjohnson** [comment]
These are now shown as variable names, not concept IDs. Closing this.
