### ISSUE TITLE
MRN trajectory

### ISSUE THREAD

**Issue by jonasalmeida** [episphere/connect#29]
Identified by Allen Malone as a trajectory at the Connect in person [IT breakout session](http://bit.ly/reportConnectIT). 

Dashboard experiments welcome, such as https://episphere.github.io/dashboard/mrn.

**Comment by theEIC** [comment]
I believe it was MRN. Changing title to reflect that.

**Comment by Eusuf2000** [comment]
We, Henry Ford, will like to have the participants provide their MRNs if known. Not required. But nice to have. HFH MRNs are 8 characters long. All numeric. Sometimes there are leading 0's and sometimes there are dashes between digits for easier reading. There is no need to do any validation - just enough length so that no data loss.  Thanks

**Comment by Eusuf2000** [comment]
On 2nd thought - we do not need HFH MRN from participants. Please do not prompt them for this... Thank you.

**Comment by danielruss** [comment]
ok to close this issue?
