### ISSUE TITLE
Biospec - Dshbrd - Scanning on the Tube Collection Screen Issue

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#396]
When scanning in the tubes collected the scanner will automatically "Enter" after the scan and move onto the next box for the scanning.  This is fine, but when you are scanning in the biohazard bags it will automatically Save and go to the review screen with the "Enter".  Can we change this so it will stay on the page?  most labs will have their scanners set up to automatically enter when data is scanned.

**Comment by StephanieWeinstein** [comment]
FYI, on the Collect/Process page, I held back on the two serum tubes in my first pass, and then went back and added them later. On my second pass, when I scanned in the second serum tube, I was automatically brought to the review page.  So this issue is not only happening when scanning in the bags, I think it happens when scanning in the last open scan field.

**Comment by anthonypetersen** [comment]
* need to try to remove the simulation of "moving on"
* still want to mimic "saving" with each scan

**Comment by anthonypetersen** [comment]
Decision was made that we should not attempt to continue when scanners send an "enter" key, this applies for every tube specimen ID entry field. It was also requested that after we scan a specimen ID we automatically tab to the next entry field that is enabled. Finally it was determined that it is not necessary to make an API Save call after every single scan.

**Comment by anthonypetersen** [comment]
changes pushed to dev

**Comment by StephanieWeinstein** [comment]
works great, thank you!
