### ISSUE TITLE
Create Human Readable Connect ID that can be referenced by IHCS/NCI/NORC

### ISSUE THREAD

**Issue by geetajoshi2019** [episphere/connect#4]
Create Human Readable Connect ID that can be referenced by IHCS/NCI/NORC.

We discussed this with Praful and he said he will analyze if last 12 Alphanumeric of UUID can be made unique.

**Comment by meshferg** [comment]
Best practice is that the ID that acts as the "primary key" for an object and a human readable ID are separate variables. The primary ID is immutable and contains no semantics (e.g. a UUID). A human readable ID can (and probably should) contain semantic fields, like the source institution. The system should allow the human readable IDs to be mutable, because mistakes get made, situations change, etc.. Also, there may be more than one human readable ID, e.g. additional human readable IDs for AoU, an internal IHDS study, who knows.

**Comment by meganstead** [comment]
Updating issue to reflect current status.

Requirements - [https://nih.app.box.com/file/536288139615]

Related to #39

**Comment by bhaumik55231** [comment]
Done!

**Comment by danielruss** [comment]
This appear to be completed.  Closing issue.
