### ISSUE TITLE
Biospec - Dshbrd - Specimen Link drop 4 sequence #'s at end

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#402]
On the Specimen Link page, where you scan in the Collection ID from the Label Sheet please program it so it only captures the "CXA123456" and not the last four digits.  For example, the user may scan in CXA123456 0000 or CXA123456 0014.  We would like the 0000 or 0014 to be dropped and only the CXA123456 to be captured.

**Comment by StephanieWeinstein** [comment]
Hi Tony,
We would like this same change made to the specimen search as well.
Stephanie

**Comment by anthonypetersen** [comment]
pushed to dev

**Comment by StephanieWeinstein** [comment]
I tested this, I think it is good for our purposes, but I'd like to confirm with the others.  It looks like it still pulls in all the numbers from the label (including the last four) but the system does move forward with the next step so that is probably fine.  (It does not require you to delete the last 4 before moving on which is good).

**Comment by StephanieWeinstein** [comment]
Its all good, thank you!
