### ISSUE TITLE
Biospec - Dshbrd - Variable/Concept ID needs

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#405]
This issue is to help track if variables/concept IDs are needed in the Data Dictionary and if there are any questions about the function of specific variables.

1: Variable/Concept ID is needed for Followup1.  This is a visit variable for the 1st visit after the baseline visit.

2: Check-In Time Display.  Question came up on if Check-In time is displayed.  Answer is yes, Check-In date and time are displayed on the Check-out screen.

**Comment by wyattks** [comment]
I have added additional variables that are needed for the Biospecimen and BPTL dashboards in the document below:

[Data Dictionary needed additions for Biospecimen and BPTL.xlsx](https://github.com/episphere/connect/files/7816713/Data.Dictionary.needed.additions.for.Biospecimen.and.BPTL.xlsx)

**Comment by brotzmanmj** [comment]
Kathleen, can you clarify whether these are variables that we have in the dictionary with concept IDs but were not showing up on the dashboard, or whether these are all new variables that we need added to the dictionary and need concept IDs for? And for the new deviations, are they applicable to all tubes, since those are nested at the tube level?

**Comment by wyattks** [comment]
These are all variables not listed in the data dictionary and need to be added.  The tubes they are related too are in the document listed in Issue #433.
