### ISSUE TITLE
verification

### ISSUE THREAD

**Issue by danielruss** [episphere/connect#46]
for each site, are they recording the verification in their system and pushing to us via api? In batches or one participant at a time? Will any site be verifying participants directly within our dashboard as it currently displaying and if so do we need to display more data from the user profile, as well as the study id, token, pin, what else? Each site needs to set up their system for verification, tell us their needs, program and test.

**Comment by danielruss** [comment]
We need the sites to push us information about the verification (e.g. was it by algorithm or manual, if not verified reason why- we will provide categories). When and how do we get this info?

**Comment by Eusuf2000** [comment]
•	We’ll send verification status through API. It can happen in batches as well as one participants at a time (walk-ins). 

•	If any potential participant walks in to the clinic and we identify him/her as an active participant because they have a PIN then we will help them complete the NCI process until questionnaire is done. An on-demand API call will be invoked to get participant(s) info from NCI for verification.

•	We would also like to have this verification capability on NCI dashboard. It should display all the information NCI has on the participant. This information would be required for further manual verification.

These data elements are needed from NCI for verification:
	Study ID* (when available)
	PIN* (when available)
	First Name*
	Middle Name* (if available)
	Last Name*
	DoB*
	Gender/Sex*
	Zipcode*
	Email*
	Phone*
	Last 4 of SSN* (if possible)

More data we get the better it is for verification.

* = Required field

**Comment by Eusuf2000** [comment]
> We need the sites to push us information about the verification (e.g. was it by algorithm or manual, if not verified reason why- we will provide categories). When and how do we get this info? 

•	We can send the verification status on nightly cycle through API. It will contain verification method (automatic/manual) and if not verified it will also have a reason why based on NCI categories.

**Comment by Eusuf2000** [comment]
Question for the team - 

- During verification update, can we pass additional information to NCI? Suppose, we manually verified a participant. We noticed that NCI had incorrect participant information (name, birthdate, or anything else) during manual verification. We corrected our end. How can we send this updated information to NCI?

**Comment by Eusuf2000** [comment]
Another question -

- Suppose the participant selected wrong site (i.e., selected Henry Ford but not a Henry Ford patient and lives in South Dakota), how do we pass this information back to NCI?

**Comment by hzhao392** [comment]
Will be managed in features spreadsheet
