### ISSUE TITLE
Formatted Biospecimen Table SST1 and SST2 missing columns

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#491]
In the Data file, the SST1 and SST2 tubes are missing columns for some of the deviations.

SST 1 is missing the following deviations in the data file: 
Discard  (record in comments)
Cent. speed/force too high
Cent. speed/force too low
Mislabeled- discard  
Mislabeled – resolved  
Not Found   
unexpected  tube size or type
Outside of tube  contaminated 

SST 2 is missing the following deviations in the data file: 
Discard  (record in comments)
Mislabeled- discard  
Mislabeled – resolved  
Not Found   
unexpected  tube size or type
Outside of tube  contaminated

**Comment by wyattks** [comment]
Forgot to add,  There is one deviation missing for the mouthwash in the table:
Less than 30 seconds deviations

**Comment by brotzmanmj** [comment]
Basically what we are finding is that we entered data for some of the new deviations (Kathleen listed above) in our data testing, and we are not seeing those deviation variables at all in the CSV file. So we're not sure if the data weren't actually captured on the dashboard when we entered it or if the variables were mistakenly not included in the CSV file.

**Comment by zly2021** [comment]
SST 1/2 Discard  d_299553921/703954371.d_248868659.d_810960823 was just added to big query flat table. It wasn't added because we can't find this concept id at https://episphere.github.io/conceptGithubActions/web/810960823 
SST 1 Cent. speed/force too high is in the merged csv file, Madhuri can point it out
SST 1 Cent. speed/force too low is in the merged csv file, Madhuri can point it out
SST 1/2 Mislabeled- discard d_299553921/703954371.d_248868659.d_684617815 was just added to big query flat table. It wasn't added because we can't find this concept id at https://episphere.github.io/conceptGithubActions/web/#684617815
SST 1/2 Mislabeled – resolved d_299553921/703954371.d_248868659.283900611 was just added to big query flat table. It wasn't added because we can't find this concept id at https://episphere.github.io/conceptGithubActions/web/#283900611
SST 1/2 Not Found d_299553921.d_248868659/703954371.d_982885431 was just added to big query flat table. It wasn't added because we can't find this concept id at https://episphere.github.io/conceptGithubActions/web/#982885431
SST 1/2 unexpected  tube size or type d_299553921/703954371.d_248868659.d_777486216 was just added to big query flat table. It wasn't added because we can't find this concept id at https://episphere.github.io/conceptGithubActions/web/#777486216
SST 1/2 Outside of tube  contaminated d_299553921/703954371.d_248868659.d_313097539 was just added to big query flat table. It wasn't added because we can't find this concept id at https://episphere.github.io/conceptGithubActions/web/#313097539

**Comment by mnataraj92** [comment]
I will add the above variables that weren't previously in the biospecimen table and let you know when I send it out.

**Comment by zly2021** [comment]
I just remembered the reason why these variables are not added in. It has been a long time since I developed the code. Since I was not sure these variables exist or not, I have two choices: add them in or leave them out. If I add them in and the variables turn out not existing, the SQL would fail since we select something not existing. Rather than risking the query not run, those variables were left out.

**Comment by brotzmanmj** [comment]
Thanks @zly2021 for the explanation. Now that the variables do exist, hopefully the query runs fine.

**Comment by wyattks** [comment]
@zly2021 One more deviation is mossing: Mouthwash -  Less than 30 seconds deviations
Concept ID 248868659
Please add this one as well.

**Comment by StephanieWeinstein** [comment]
There is a deviation called "Mouthwash Tube 1- Deviation Mouthwash" in column DP which is populated with a "yes" for one of my participants who had the "Mouthwash - Less than 30 seconds" deviation.  I wonder if this deviation is just poorly named and is in fact the deviation that we thought was missing?  If so, it needs to be relabeled!

**Comment by mnataraj92** [comment]
@StephanieWeinstein I just checked and yes it is that variable! I will rename it. I wonder if it's because the label was too long and got cut off, but I'll fix that in the code.

**Comment by StephanieWeinstein** [comment]
great, thank you!
