### ISSUE TITLE
Formatted Biospecimen Table Data issues for one Participant

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#495]
Connect ID 12346342159 had 3 visits associated with it.
Baseline: CXA123422
Follow-up 1: CXA123424
Follow-up 2: CXA225588
There are a few issues with the Baseline data on these samples.  Under the Baseline blood sample collected (Column MY), Baseline Mouthwash Collected (column NA) and Baseline Urine Collected (column NC), it states No but all of the baseline samples were collected.  Under the Baseline Date/time columns (MZ, NB and ND) the dates and times listed are for the Follow-up 2 collections and not the original Baseline collection.
See attached File

[Particpant 1246342159 data.xlsx](https://github.com/episphere/connect/files/8188940/Particpant.1246342159.data.xlsx)

**Comment by brotzmanmj** [comment]
@mnataraj92 In the merged CSV file, we are only able to find variables for what appears to the be the baseline check-in flag and the baseline check-in and check-out timestamps. We didn't find those variables for Followup 1 and Followup 2 visits for this person. Can you see if you can find those and add them to the CSV file for when we retest this scenario?

**Comment by brotzmanmj** [comment]
@mnataraj92 The other main concern with this participant's data which you pointed out is that the derived variables for Baseline Collection of blood, urine, and mouthwash are No even though all three baseline samples were collected. Also the corresponding date/time variables are populated despite the collection being 'No'. Because this was one of the few samples we entered with Baseline, Fup1 and Fup2 samples were entered we're concerned that maybe the derivation of the Baseline summary variables perhaps aren't working right when Fup samples exist. Can you check it from this perspective?

**Comment by zly2021** [comment]
When we query from dev participants table using "select * from Connect.participants where Connect_ID=12346342159", it returns no results. We have trouble locating this Connect_ID

**Comment by wyattks** [comment]
Would participant name help?

**Comment by wyattks** [comment]
Sorry it looks like an extra 3 got in there.  The Connect ID is 1246342159.

**Comment by zly2021** [comment]
When I check with Madhuri together today, the value changed from No to Yes for the collection flag already

**Comment by wyattks** [comment]
Data is now correct for these 3 collections.
