### ISSUE TITLE
Missing or incorrect date/time information for some of the samples

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#498]
There are two issues- 

1 - date/times are duplicated for multiple visits for one participant.  For Connect ID 1246342159, there were 3 visits (Baseline, Follow-up 1, and Follow-up 2) all 3 have the same check-In date/Time and the same check-out date/time.  The date/time associated for  blood collected, mouthwash collect, urine collected, Check-In and Check-Out are all reflecting the dates and times for Follow-up 2.  The data for the "Collection date/time" was correct.

2 -  CXA123438 is missing the collection dates/times for the Mouthwash and Urine collections.  The baseline blood was not collected for this participant but Mouthwash and Urine were. 

Attached is a file showing the captured dates/times vs the expected dates/times

[Date Time Issues.xlsx](https://github.com/episphere/connect/files/8207284/Date.Time.Issues.xlsx)

**Comment by brotzmanmj** [comment]
@anthonypetersen 
For 1- To clarify: The date/time stamps listed above are actually correct because the variables in the CSV file are all Baseline variables. What we need is for @mnataraj92 to add to the biospecimen merged CSV file the variables for the fup1 and fup2 check in/out flag and time stamps so we can confirm if those are also correct.

**Comment by mnataraj92** [comment]
Hi @brotzmanmj, the variables that were added to the merged csv file were based off of the variables that were available in the biospecimen table from BQ. If variables are missing, it's likely because there wasn't any data in the table for those variables. I'm not sure if more data has been added since I pulled the biospecimen table last week. But I would need the variables needed to be in the biospecimen table already so I know what the nesting looks like

**Comment by brotzmanmj** [comment]
@mnataraj92 The check in/out flags and date/time stamps would be in Participant Table rather than the biospecimen table, and they would have been populated in our data testing for a few participants that we put in followup samples for. @anthonypetersen Can you point Madhuri to where those variables are?

**Comment by anthonypetersen** [comment]
@mnataraj92 @brotzmanmj a concept entry for the specific visit won't be present until that participant has checked in for the specific visit for the first time

**Comment by brotzmanmj** [comment]
@mnataraj92 Connect ID 1246342159 checked in for baseline, fup1, and fup2 so all three visits should have a concept entry for these specific visits. If you can't find them in BQ, then suggest following with the Zhuoliang to see if they were included in the extraction and flattening. Thanks.

**Comment by wyattks** [comment]
related to issue #495

**Comment by wyattks** [comment]
Data is now reflected correctly
