### ISSUE TITLE
Chicago Shipping error

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#530]
When Chicago was testing the dashboard with a shipment they had an error.  They scanned in CXA000123 0009.  All the Blood and Urine tubes populated into the package with that ID.  The mouthwash was unable to be scanned into a box.
I have attached the manifest showing the error. 
Stephanie has asked them to join the office hours (10 - 11am) tomorrow to see if we can trouble shoot with them on what exactly happened.

[Manifest1_20220525.pdf](https://github.com/episphere/connect/files/8774635/Manifest1_20220525.pdf)

**Comment by HopkinsDC** [comment]
Screenshots of issue from Chicago (taken 5/26)

![Screen Shot 2022-05-26 at 10 52 49 AM](https://user-images.githubusercontent.com/85250133/170516574-509fa2e0-e3c2-493b-8be9-2744121b5d96.png)
![Screen Shot 2022-05-26 at 10 53 05 AM](https://user-images.githubusercontent.com/85250133/170516575-a051ab84-45ee-4fb6-8571-77f1086def11.png)
![Screen Shot 2022-05-26 at 10 53 16 AM](https://user-images.githubusercontent.com/85250133/170516577-f48f4d1a-ac90-4ee8-bbc7-73970c4e23bd.png)
)

**Comment by StephanieWeinstein** [comment]
we talked with Chicago this morning and now have a better handle on their issues. Here are some additional comments:

for subject with collection ID CXA000123, Chicago put the blood and urine tubes into bag 0008 as directed.  Their screen shot of the collection review screen shows that the bag went in as 0008. When they scanned that bag for shipping, it scanned as 0009 but still pulled up all the proper blood and urine tubes that belong in that 0008 bag.  They didn't notice an error until they saw on the manifest that it was showing as 0009.

Today when we met we asked them to enter the 0008 bag in again (first screen shot) and it shows that the system still thinks that bag is in Chicago, even though the samples show on the manifest of the package that went out.

They also had issues sending the mouthwash samples for this participant because when the scanned the 0009 bag they got an error (second screen shot) which makes sense if the system thought that the 0009 bag was already shipped.

We told them they can scan individual specimens, not just bags, so when they did that (third screen shot) they could see the 0007 mouthwash samples still in Chicago (they didn't ship that one, so this makes sense).

Gene looked in the back end and the data show the 0009 bag with the blood and urine tubes.

**Comment by wyattks** [comment]
Closing for Now.  Warren updated a code he believes may have caused this.  I cannot replicate the issue.  Will reopen if this happens again.
