### ISSUE TITLE
KP Clinical Incentive Eligibility Criteria

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#552]
Participants with KP Clinical collections will be eligible for incentives if any baseline clinical blood tube was collected (per entry into our dashboard) OR if the KP variable for baseline 'Blood Collected' pushed to us from KP via API = Yes.

**Comment by wyattks** [comment]
Will not populated in the dashboard.  This will be stored as incentive eligible and NORC incentive eligible.  This needs to populate variables behind the scenes.

**Comment by FrogGirl1123** [comment]
@geniosys CID 693370086 (Clinical Site Blood Collected) will be pushed from KP.  878865966 (BioFin_BaseBloodCol_v1r0 ) is the flag for baseline blood collected for the research collection.  In order to trigger the incentive, 731498909 (Eligible for Payment), 693370086 will need to be added to the derivation for 731498909 (Eligible for Payment) or the derivation for  878865966 (BioFin_BaseBloodCol_v1r0 ), since 878865966 (BioFin_BaseBloodCol_v1r0 ) is already part of deriving Eligible for Payment. Eligible for payment is the flag used by NORC to determine if the participant qualifies for an incentive (payment).  Take a look at these variables in the MasterSurveyCombo dictionary and let me know which path you would like to use to incorporate 693370086 (Clinical Site Blood Collected) into the Eligible for Payment flag.

**Comment by geniosys** [comment]
@FrogGirl1123 Thank you. I think much of the logic was already set, so all I had to do is add a condition that would either trigger the research or clinical.

**Comment by brotzmanmj** [comment]
Was the logic updated to include the variables coming from KP via API?

**Comment by Davinkjohnson** [comment]
Hendrick has some more changes to make to the logic. Will update team when they're ready

**Comment by geniosys** [comment]
@Davinkjohnson @brotzmanmj I updated the logic to include today's discussion input.

**Comment by Davinkjohnson** [comment]
All Dashboard items look good. We still need to verify the KP sent variables

**Comment by Davinkjohnson** [comment]
Domonique to check this today for KP soft launch participants.
