### ISSUE TITLE
Cannot Link a Collection ID on the Clinical Dashboard

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#555]
in the Clinical dashboard, when you search for a participant, the "Continue to Specimen Link" button is missing on the search results page.  There is no way to get to the Specimen Link page currently on the Clinical dashboard.  Please add the "Continue to Specimen Link" button to the Participant Search Results page.

[Clinical Search Results Page with Specimen Link Button.docx](https://github.com/episphere/connect/files/9152049/Clinical.Search.Results.Page.with.Specimen.Link.Button.docx)

**Comment by geniosys** [comment]
Ok, so I found something interesting from what I see in the codebase, the "Specimen Link" button is only displayed when there's already a check-in visit. If there's no check-in visit, then the "specimen link" button won't appear.

Now adding the "specimen link" button like i did in the clinical dashboard won't be helpful as it won't be opening the specimen tab since that very same tab is dependent on the visit. So I think we need a new workflow specific to the clinical dashboard.

**Comment by Davinkjohnson** [comment]
On hold until Kathleen delivers updated workflow

**Comment by wyattks** [comment]
Attached is a basic workflow for the Clinical dashboard.  Please le me know if you need it to be more detailed.

[Clinical Data Entry Workflow.docx](https://github.com/episphere/connect/files/9168505/Clinical.Data.Entry.Workflow.docx)

**Comment by wyattks** [comment]
Confirmed this is working in Dev

**Comment by wyattks** [comment]
Ready for stage
