### ISSUE TITLE
Change Collection Location HFHS Research Clinic (Main Campus) to HFH K-13 Research Clinic 

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#564]
Henry Ford has asked us to change the Collection Location HFHS Research Clinic (Main Campus) to HFH K-13 Research Clinic as it will give them more context to where they physically collected the samples.
We need it changed in the following places:

- Biospecimen Dashboard Specimen Link Drop Down (Davin to assign)
- Biospecimen BPTL CSV (Abhinav)
- Data Dictionary update of the label (Nicole's team)
- Metrics format Code (Jing)
- BSI (Kathleen) - This needs to be done when the csv is complete and pushed to production

**Comment by brotzmanmj** [comment]
The Concept ID should remain the same, just the label needs to change. Thanks.

**Comment by abhinavjonnada82** [comment]
Site name changed on DEV

**Comment by brotzmanmj** [comment]
Kirsti at HFH tested this in dev and it looks good. Ready to push to stage. 
Remaining things to do are:
@wyattks update BSI so it will accept the new location as in the CSV file 'HFH K-13 Research Clinic'. 
@FrogGirl1123 update the Data Dictionary for concept ID for the Collection Location (variable 951355211, response code 7361830940) to 'HFH K-13 Research Clinic' instead of 'HFHS Research Clinic (Main Campus), and Jing to update the format code for this

**Comment by wyattks** [comment]
BSI has been updated.

**Comment by wyattks** [comment]
Ready for Production

**Comment by brotzmanmj** [comment]
Noting that this in production now, but we still have these two subtasks before close out:
@FrogGirl1123 update the Data Dictionary for concept ID for the Collection Location (variable 951355211, response code 7361830940) to 'HFH K-13 Research Clinic' instead of 'HFHS Research Clinic (Main Campus) 
and
Jing to update the format code for this response code

**Comment by wyattks** [comment]
@jeannewu yes that is correct

**Comment by jeannewu** [comment]
Got it. Thanks.

**Comment by brotzmanmj** [comment]
@FrogGirl1123 Please update the Data Dictionary for concept ID for the Collection Location (variable 951355211, response code 7361830940) to 'HFH K-13 Research Clinic' instead of 'HFHS Research Clinic (Main Campus)'

**Comment by FrogGirl1123** [comment]
The update has been made to the data dictionary.  Pleas be sure to tag Madhuri in requests for data dictionary changes as she often has more bandwidth.
