### ISSUE TITLE
Update Site Location Names in Research Dashboard (Sanford)

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#584]
Please rename “SF Cancer Center LL” to “Imagenetics Building” for Sanford's Collection Location, Shipping Location, and the manifest.

**Comment by brotzmanmj** [comment]
We need clearer direction for the team on this. Are you referring to the shipping location or the collection location? We already updated the collection location for HFH to reflect K13 so that change is done. For the Sanford change is the change requested for the collection location, the shipping location, or just on the manifest?

**Comment by HopkinsDC** [comment]
Added this to #582
