### ISSUE TITLE
Dashboard Bug - Participant Search Results with DOB

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#596]
HealthPartners reported that they had 2 participants (Connect ID #4746725273 and #3872439399) on 11/16/2022 where the participants did not come up in the search when the first name, last name, and DOB were entered or when just the DOB was entered. HealthPartners triple-checked that the participants' information was entered correctly into the search fields. The participants did come up in a search when the phone number was used in the search. The rest of our participants on 11/16/2022 resulted in successful searches using First name, last name, and DOB.

**Comment by Davinkjohnson** [comment]
Also refer to https://github.com/episphere/connect/issues/594 

for further details on search requirements

**Comment by brotzmanmj** [comment]
Abhinav and Michelle investigated and we found out what is happening. When a component of the date of birth (separate month, day, year) is corrected in the SMDB prior to verification as part of the verification process, it is just updating those individual variables and is not updating the concatenated DOB (concept ID 371067537). The participant lookup on both the SMDB and the Biospecimen Dashboard is searching the concatenated DOB, and therefore it is not finding the result upon search of the corrected DOB. Abhinav is working on a fix so that, going forward, changed to month, day or year made on the SMDB interface will also update the concatenated DOB variable. When implemented, this will fix those going forward. It will not fix those already in prod that have had DOB corrected in the past. Abhinav is looking at prod to see how many of those there are and then we will discuss the most expeditious way to fix them.

**Comment by abhinavjonnada82** [comment]
They're 23 participant on prod with different DOB. Resolution: Tony would them to the Prod Manual Change Log.

**Comment by HopkinsDC** [comment]
Erin from HealthPartners tested the following scenarios:

1. If only the First Name is entered, the search should return all participants with that first name.
2. If only the Last Name is entered, the search should return all participants with that last name.
3. If both the First and Last names are entered, the search returns all participants with that first and last name combination.
4. If only the DOB is entered, all PTs with that DOB should be returned.  

She received the "Participant with entered search criteria not found!" message when searching on first name only, last name only, and first + last name only. The DOB search, however, worked as expected and pulled multiple participants up with the same DOB.
