### ISSUE TITLE
Add Deviations to Box Manifests 

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#609]
Please add the deviation type to the box manifests between the "Type/Color" column and the "Scanned By" column. See image below for mock-up)

The deviation type should also appear on the box manifest as it is being printed in the shipping dashboard and when the manifest button is clicked in "Packages in Transit from Site" in the BPTL dashboard.

![Picture1](https://user-images.githubusercontent.com/85250133/214678502-c6ec1e24-f3e2-4615-a838-c16994d3d6ad.jpg)

**Comment by StephanieWeinstein** [comment]
Can we also include any comments that are entered, both for individual tubes and for the whole collection?

**Comment by HopkinsDC** [comment]
@StephanieWeinstein They may not have enough room page-wise to add all three. We can ask next week.

**Comment by anthonypetersen** [comment]
* Add columns for Tube Deviations, Tube Comments, and Collection Comments
* Will review changes as they are implemented

**Comment by Davinkjohnson** [comment]
@Gbarra9 To review this week. re-group next week on size/estimate

**Comment by Davinkjohnson** [comment]
Gene continuing to work on this. Should have PR ready for DevOps this week. (3/8 target)

**Comment by Davinkjohnson** [comment]
Hoping to have DEV PR today 3/28

**Comment by Gbarra9** [comment]
The Deviation Type column is added in 3 manifest locations 

- Shipping Dashboard's Box Manifests
- BPTL's Package In Transit
- Reports Shipping Manifest)

Let me know if the Deviation Type needs to be removed for the Reports Shipping Manifest. 

For testing can you please include Full Specimen Id's **(Ex. CXA426800 0001**) with more than one deviation type.

If I recall correctly as of now, Full Specimen Id's with the below deviations are to be avoided since they do not get added into the shipping dashboard. 

- Broken (discard do not ship)
- Insufficient volume, discard
- Mislabeled - discard
- Discard (record in comments)
- Not found

**Below is an image of the Deviation Type with test data.** 
<img width="1281" alt="Screenshot 2023-03-28 at 2 23 07 PM" src="https://user-images.githubusercontent.com/33293205/229010504-d3a8cc79-c5d2-4021-90cd-fd6c6387cad7.png">




Thank you very much.

**Comment by HopkinsDC** [comment]
Deviations and comments were added to the box manifest successfully in dev. Ready for stage.

**Comment by Gbarra9** [comment]
**Replaced `Shipped By` Column to `Comments` Column**

Packages In Transit Manifest
![Shipping Manifest Packages In Transit](https://user-images.githubusercontent.com/33293205/234156467-bfbe1723-23f1-43e7-85df-aec75865766a.png)

Box Manifest
![Screenshot 2023-04-24 at 6 14 11 PM](https://user-images.githubusercontent.com/33293205/234156605-fe030505-85c2-4f89-8c0a-4c4ad00d36c5.png)

**Comment by Gbarra9** [comment]
This was a test on my part to keep the `Scanned By` column. It looks too compact in my opinion.

Packages In Transit Manifest
![Screenshot 2023-04-24 at 9 16 02 PM](https://user-images.githubusercontent.com/33293205/234157533-8f20250a-7f02-498f-ae52-d36b0d71712c.png)



Box Manifests
![Screenshot 2023-04-24 at 5 55 10 PM](https://user-images.githubusercontent.com/33293205/234157264-800fadb8-6f8a-4875-b8a7-3aed4972c22e.png)

**Comment by HopkinsDC** [comment]
@Gbarra9 I agree. Please keep the deviation type and comments columns and remove the scanned by column from the box manifest.

**Comment by HopkinsDC** [comment]
@Gbarra9 The changes have been successfully made in dev. Ready to push to stage.

**Comment by Davinkjohnson** [comment]
Approved in Stage, ready for PROD

**Comment by HopkinsDC** [comment]
Pushed to prod (5/26)
