### ISSUE TITLE
Add "App Version" Visuals

### ISSUE THREAD

**Issue by anthonypetersen** [episphere/connect#621]
In the past, we have been working through issues with sites only to find that they weren't running the most up-to-date versions of our code base.

For each of our client-facing repositories, add logic that will display a version number (somewhere small and out of the way) that will allow us to easily identify which "version" of our code is being run. Build the logic so the version numbers can be easily updated prior to stage / production pushes.

**Comment by we-ai** [comment]
Discussed with @anthonypetersen earlier today, and we concluded that (instead of using different versions in our different repos) a new format of version is needed. The version should be simple and clear, so that it's easy to understand and update.

For our July release, one possible format can be `v24.7.0`, meaning formal release of July, 2024. If fixes are needed after format release, the version can be updated to `v24.7.1`, `v24.7.2` etc. 
Please comment on this @Gbarra9 .

**Comment by Gbarra9** [comment]
> For our July release, one possible format can be `v24.7.0`, meaning formal release of July, 2024. If fixes are needed after release, the version can be updated to `v24.7.1`, `v24.7.2` etc.

@we-ai  I have no objections to the formatting you suggested.

**Comment by Gbarra9** [comment]
(Biospecimen, SMDB, connectApp)  - tested in dev and ready for stage

**Comment by wyattks** [comment]
Kirsti verified shesees the version in Stage.  Ready for prod

**Comment by sonyekere** [comment]
In production.
