### ISSUE TITLE
Post Destruction - PWA

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connect#662]
This will be to track remaining work related to the Post-Data Destruction requirements for MyConnect (PWA).

- Need to add in Withdrawal account lock down (Pts should not be able to submit data as soon as SMDB request is submitted)
- Navigation preference:
    - Land on dashboard (maintain current functionality)
    - Ideally: gray out all other tabs except for Form
    - MVP: remove/hide all other tabs
- Keep Dashboard locked down (Joe’s example)
- My Forms - Enable this page
    - Be able to see: (HIPAA, Consent, HIPAA revocation, Data destruction)
    - Leave the data destruction request accessible
- MyProfile - Disable this page

**Comment by brotzmanmj** [comment]
For this one: Need to add in Withdrawal account lock down (Pts should not be able to submit data as soon as SMDB request is submitted) requirements are as follows: For participants who are Withdrawn (HdWd_WdConsent_v1r0 Concept ID 747006172 = 353358909 (Yes)), as soon as we receive the withdrawal flag, on the PWA dashboard page instead of the surveys, display a message that says 'You have withdrawn from Connect per your request. If you have any questions, please contact the Connect Support Center (phone number)." Deanna will finalize the wording. The surveys will no longer be visible. The other parts of the app will still be accessible. For those who are withdrawn AND also requested data destruction, this same requirement applies. Then after the data destruction occurs, the message will change to the one saying their data has been destroyed per their request and only the Forms tab should remain accessible.

**Comment by depietrodeanna** [comment]
@jhflorey For participants who are Withdrawn, as Michelle described above, implement this message: 

"You have withdrawn from Connect. We will not collect any more data from you. If you have any questions, please contact the Connect Support Center by calling 1-877-505-0253 or by emailing ConnectSupport@norc.org."

For those who are withdrawn AND requested data destruction, the same message and access requirements apply. 

After data destruction occurs (60 days passes OR they sign the data destruction request form), the Forms tab is the only one they should retain access to and the message displayed will change to: 

"At your request, we have deleted your Connect data. If you have any questions, please contact the Connect Support Center by calling 1-877-505-0253 or by emailing ConnectSupport@norc.org."

**Comment by depietrodeanna** [comment]
@jhflorey @Davinkjohnson Looks good in Dev. Tested multiple scenarios.

**Comment by robertsamm** [comment]
Tested in stage, ready for prod.
