### ISSUE TITLE
Missing Tube-Level BPTL Received Dates in Biospecimen Table

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/connect#819]
*Repeat occurrence of #653* 

The following Connect IDs are missing at least one tube-level BPTL received date in the biospecimen table. The received dates _are_ present in the Boxes table.

- 9375710580 (HFH)
>- BioBPTL_DateRec_v1r0_MW1
Record Date = 2022-06-24T00:00:00.000Z

- 3080768933 (HFH)
>- BioBPTL_DateRec_v1r0_MW1
Record Date = 2022-06-24T00:00:00.000Z

- 3409243008 (UCM)
>- BioBPTL_DateRec_v1r0_SST1
>- BioBPTL_DateRec_v1r0_SST2
>- BioBPTL_DateRec_v1r0_EDTAT1
>- BioBPTL_DateRec_v1r0_HT1
>- BioBPTL_DateRec_v1r0_ACDT1
>- BioBPTL_DateRec_v1r0_MW1
Record Date = 2023-10-23T00:00:00.000Z

-8193439990 (MFC)
>- BioBPTL_DateRec_v1r0_HT1
>- BioBPTL_DateRec_v1r0_ACDT1
Record Date = 2022-11-09T00:00:00.000Z

- 5743151720 (MFC)
>- BioBPTL_DateRec_v1r0_EDTAT1
Record Date = 2023-07-11T00:00:00.000Z

**Comment by sonyekere** [comment]
DevOps and Bioospecimen team to connect 11/14

**Comment by JoeArmani** [comment]
This issue is tough to diagnose because there doesn't seem to be a pattern to the failed writes.

There was a potential issue with the db write operation. These writes were being executed separately and individually, in a way where some could succeed, others could fail, and the user processing the package receipt wouldn't know anything was amiss.

This update will restructure the way the write operation is handled. The receipted box and specimens in the box will be written in a batch - either 100% pass or 100% fail. Error handling will be implemented to trace any error's source and show a useful error message in the BPTL dashboard. This way, if we have future errors, we'll have a better handle on the source. In the failed cases, it's possible a simple retry will succeed.

Additionally, we're implementing a check to make sure a box hasn't already been marked received. This should solve the possibility of accidentally scanning a tracking number twice in the 'package receipt' form. Now, if a package has already been received, the user will receive a warning about the already received status. Clicking 'cancel' will terminate the operation, clicking 'continue' will process the double receipt and add a `'forceWriteOverride' = true` property to the box.

The PR should be out for review tomorrow. Please let me know if any changes are requested to this update.

Box - accidental double receipt screenshots (from dev):
<img width="1185" alt="Screenshot 2023-11-16 at 4 04 34 PM" src="https://github.com/episphere/connect/assets/93854858/b7d832b7-b660-4022-964b-36f4074c0976">
<img width="964" alt="Screenshot 2023-11-16 at 4 06 08 PM" src="https://github.com/episphere/connect/assets/93854858/21fd95cb-a290-4744-8d30-15c0782c0c4c">

**Comment by JoeArmani** [comment]
Update: After discussion with @HopkinsDC, the desired behavior on override (2nd receipt):

(1) received specimens: use new date or retain old date? --- **Retain old date** 
(2) unreceived specimens: use new data or use old date? --- **Use new date**
(3) Full specimen received timestamp: use new date or retain old date? --- **Retain old date**  
(4) box received timestamp: use new date or retain old date? --- **Retain old date**

**Comment by sonyekere** [comment]
Work is still ongoing - 11/28 Dec release. Sandra to add to Punchlist.

**Comment by JoeArmani** [comment]
Re: GitHub Project Board - This issue moves alongside https://github.com/episphere/connect/issues/834. I'm leaving this out of the 'reviews' sections to avoid confusion.

**Comment by JoeArmani** [comment]
PRs ready for review.
Biospecimen: https://github.com/episphere/biospecimen/pull/633
ConnectFaas: https://github.com/episphere/connectFaas/pull/487

**Comment by HopkinsDC** [comment]
Issue tested in dev. Ready for stage.

![Screenshot 2023-12-12 at 11 37 26 AM](https://github.com/episphere/connect/assets/85250133/666e76cf-b71e-4d26-bbc6-dbbedf8346ee)

**Comment by HopkinsDC** [comment]
Tested in stage. Ready for production.
![Screenshot 2023-12-18 at 10 52 26 AM](https://github.com/episphere/connect/assets/85250133/7815ecfb-a457-4b63-af3b-b287d1249d0d)

**Comment by JoeArmani** [comment]
Closing - this is in prod.
