### ISSUE TITLE
Auto reset/create test accounts in dev and stage

### ISSUE THREAD

**Issue by we-ai** [episphere/connect#838]
Test accounts need to be reset/created for each round of testing various scenarios in dev and stage. The account reset/create functionality can be implemented in SMDB. Below are tentative requirements:
- Authenticated SMDB users are allowed to do it
- Multiple accounts can be reset/created in a single UI page
- Provide options to reset/create an account to a specific stage: brand new, verified, consent forms submitted, etc

Note: 
- When doing account resets, need to check whether account age (creation time) affects account behaviors in PWA, and update it if so.

**Comment by brotzmanmj** [comment]
Undecided if will reset test accounts or create code to generate new test accounts. Putting on hold for later discussion among the team.

**Comment by sonyekere** [comment]
**Per the DevOps meeting on 7/31:** Automated testing won’t be fully integrated into the August release but will be useful for ongoing work. The plan moving forward is to reset existing test accounts rather than create new ones.

@amber-emmes will start by investigating automatic account resetting 

High Level Summary of Approach:
Begin with simple automated tests and expand based on initial findings
@Davinkjohnson Create GitHub issues to track test cases and progress
Ensure testing covers both front-end interactions and back-end data integrity
Reuse existing code where possible to streamline future updates
