### ISSUE TITLE
Clean up PROD Participants with Derivation Error - Baseline Samples Collected (Biospecimen)

### ISSUE THREAD

**Issue by abhinavjonnada82** [episphere/connect#869]
Clean up participants with derivation error in prod. 

Fix released for this issue; Derivation Error - Baseline Mouthwash Collected (Biospecimen). 
Caters to participants after December release & all 3 biospecimen samples.

Manually fix following participants with derivation to NO with no samples collected.

**Blood Sample: NONE**

**Mouthwash Sample: Update derived variable 684635302 from 353358909 to 104430631**
University of Chicago Medicine 1969243220

**Urine Sample: Update derived variable 167958071 from 353358909 to 104430631****
HealthPartners 2612518995
HealthPartners 1559086212
HealthPartners 1003010399
HealthPartners 4456006286
HealthPartners 2901018660
HealthPartners 1694845431
HealthPartners 9663139376
Henry Ford Health System 4302295915
Sanford Health 2111689227
Sanford Health 3124109576
Sanford Health 7407945553
Sanford Health 4032411374
University of Chicago Medicine 7486495243
University of Chicago Medicine 3409243008
University of Chicago Medicine 5461806718
University of Chicago Medicine 4215193310

List generated based off below condition:
Participants have NO (blood/urine/mouthwash) collections after 11/21/22 but have (BioFin_BaseBloodCol_v1r0/BioFin_BaseUrineCol_v1r0/BioFin_BaseMWCol_v1r0) derived variables set to yes

**Comment by brotzmanmj** [comment]
@abhinavjonnada82  Thank you. @mnataraj92  can you add these to the prod manual change log?

**Comment by mnataraj92** [comment]
This has been added to the prod change log https://nih.app.box.com/file/954325312156?s=b6rhrbpa6fp07trdfn0fnepnm2ybu48d

**Comment by brotzmanmj** [comment]
@mnataraj92  can you mark this change 'On Hold' in the prod manual change log? I need to confer with the Biospecimen team first about making this updates and also I see there are a couple other variables that we will need to change manually in addition to the ones above in order to fully correct the data. I'll try to complete this review today if I can.

**Comment by mnataraj92** [comment]
@brotzmanmj done!

**Comment by erincschwartz** [comment]
@brotzmanmj I have checked all of these Connect IDs in the Biospecimen table, confirmed that all only have one row of data entered

**Comment by sonyekere** [comment]
@mnataraj92 - Can you kindly give some feedback on the above (variables). Thanks!

**Comment by mnataraj92** [comment]
Hi @brotzmanmj yes, the date collected and setting variables would need to be null. 

The derivation notes in the DD also indicates that for baseline mouthwash collection, it's derived from: 
IF BioSpm_Visit_v1r0 = 0  AND MWTube1_BioCol_TubeCollected_v1r0 = 1, THEN BioFin_BaseMouthCol_v1r0=1, so would visit and tube collected also have to be null? 

For urine collection, it's derived from: IF BioSpm_Visit_v1r0 = 0  AND UrineTube1_BioCol_TubeCollected_v1r0 = 1, THEN BioFin_BaseUrineCol_v1r0=1

**Comment by brotzmanmj** [comment]
@mnataraj92 in these cases, the tube collected is already 'no' so that's fine as is. And in all of these cases there were other tubes that were collected (such as blood) so I think BioSpm_Visit_v1r0 = 0 (which means baseline) should stay as is because it applies to all the tubes collected that day.

So it sounds like only date collected and the setting just for the sample type in question (mouthwash or urine) needs to be set to null for each of these. Can you add that to the prod manual change log and I'll approve?

**Comment by mnataraj92** [comment]
perfect sounds good! i'll add that in now.

**Comment by mnataraj92** [comment]
This is in the prod change log https://nih.app.box.com/file/954325312156?s=b6rhrbpa6fp07trdfn0fnepnm2ybu48d. Please note this spans over rows 200 and 201 since this change was previously entered but placed on hold. I'll let Tony know as well since he'll have to scroll up a little.

**Comment by brotzmanmj** [comment]
@mnataraj92 I think it would be clearer if we said exactly what to change for the Mouthwash one and exactly what to change for the Urine ones, all in the same row. Can you update this in the change log?

**Comment by brotzmanmj** [comment]
@mnataraj92 also I think the CID for the setting isn't right

**Comment by brotzmanmj** [comment]
Looks better @mnataraj92 my only remaining question is for the urine samples on the list, are they are Research collections? Because the date of collection that we are asking to nullify is the research one. If they are clinical collections then we would need to nullify the clinical date of urine collection.

**Comment by mnataraj92** [comment]
let me check

**Comment by mnataraj92** [comment]
they're all research collections so we should be good

**Comment by brotzmanmj** [comment]
excellent thanks for checking! I've approved the item and will tell Tony we can take it off hold for this week.

**Comment by mnataraj92** [comment]
Sounds good! I also asked Rebecca to double check BQ on Monday (since I'll be OOO) since this is a pretty complex change log item.
