### ISSUE TITLE
KP Update Recruit Type Values

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#895]
Melanie mentioned that KP made corrections to the "Update Recruit Type" values (RcrtV_UpdateRecType_v1r0, CID state_d_793822265) for the KP sites. This change was made for 562 individuals:

SITE	N
KPCO	156
KPGA	68
KPHI	60
KPNW	278

@rebexxxxxx checked the Update Recruit Type variable (state_d_793822265) and the Recruit Type variable (d_512820379), and noticed a mismatch in the recruit type for all of the individuals this was updated for. 

When asked the reasoning and context regarding these update recruit type corrections, this was the explanation provided:

"We had a couple of issues that led to incorrect recruitment types:

1. We use the concept ID - numeric format value mappings as described in the Master data dictionary in the process of converting our data to concept IDs for API calls. For the update recruitment type field, the mappings were changed at one point and I didn't realize it when I loaded in an updated data dictionary in our data system. This led to some incorrect mappings. We had updated our production code to address the issue a while back, but we still had the incorrect values in the PWA data tables.

2. We were using a communication date field in our definition of an active recruit that was sometimes null at the time of verification due to delays from our communication vendor, which led to some active recruits being classified as passive recruits. This accounts for the majority of the records that I needed correct. We updated our production code last week so that misclassifications are less likely to happen."

Documenting here to figure out next steps.

**Comment by brotzmanmj** [comment]
1. The first issue sounds like a one-off fix of historical data that should not re-occur. It would have been better if they had some indication that the Update Recruit Type they were sending was not working/not being received correctly. I'm not sure why, if they had the wrong codes, did the call not return an error message. @Davinkjohnson  and @FrogGirl1123  is this worth pursuing or should we let it go?

2. The second one I'd like to understand a little more. Some gets set as an active recruit by our system when they send us the de-identified data for the invitation batch they are initiating. Were they sending us those data too late in their preparation process? What have they changed to alleviate that? It's important because if our system does not have the token/PIN early enough in the process such that people who were in the batch are entering as passive recruits, then they can't access their surveys right away and they also go into the manual verification workflow instead of automated which takes more staff time. I'd like more detail so we can understand what they changed and how it functions now.

**Comment by brotzmanmj** [comment]
@mnataraj92 can you give an update on this? thanks

**Comment by mnataraj92** [comment]
Nicole, Amelia, and I met with Melanie yesterday to get some more clarification on what happened and what steps have been taken to prevent this from happening again:

-The way KP translates concept IDs to values is with the Data Dictionary. Originally written to use numeric values (0, 1, 2, etc). They use a format that allows them to go from concept ID to a readable value KP wants to see on their end.
-At some point those values changed for update recruit type (likely when we added new options to the variable). So basically they were mapping to the wrong concept IDs at one point
-Since then the mapping has changed to map what the data dictionary says and KP now has a program that goes through and checks for differences with numeric values
 
-The way that recruit type works for NCI is that the function that does the update only allows for one update, so now data needs to be changed manually in prod for all of these 562 people that have a mismatched recruit type and update recruit type

@anthonypetersen what would be the best approach to change this data in prod for these 562 individuals? Is what you see in firestore/BQ enough for the recruit type (d_512820379) and update recruit type (state_d_793822265) variable, or would you like Melanie to send over what the recruit type var should be changed to for each individual?

**Comment by anthonypetersen** [comment]
@mnataraj92 for these 562 participants, which is incorrect? `Recruit Type` or `Update Recruit Type`? i.e. which variable needs to be updated for these participants?

**Comment by mnataraj92** [comment]
@anthonypetersen The update recruit type value is what was corrected - so **recruit type** is the variable that needs to be updated to match. This is the case for all records. For example, if “update recruit type” says “passive to active” but “recruit type” says “passive”, then "recruit type" should be changed to "active".

**Comment by anthonypetersen** [comment]
@mnataraj92 I'm not sure how those would've gotten out of sync based on the code we have, but if the site re-sends the values for `Update Recruit Type` the values for `Recruit Type` should auto-correct. The logic inside our `Update Participant Data` API reads as follows:

If the data passed in for `Update Recruit Type` equals `Passive to Active` and the participants current `Recruit Type` equals `Passive`, set the participants `Recruit Type` to `Active`

If the data passed in for `Update Recruit Type` equals `Active to Passive` and the participants current `Recruit Type` equals `Active`, set the participants `Recruit Type` to `Passive`

**Comment by mnataraj92** [comment]
@anthonypetersen The function only allows for one update though right? And after that it wouldn't update the values? I can ask Melanie to re-send the update recruit type values for those 562 people though and have someone on analytics check to see if the values are still mismatched.

**Comment by anthonypetersen** [comment]
@mnataraj92 oops, good call.. the logic I pointed out only applies in our `Submit Participant Data` API.

I would prefer not to manually update data for 562 participants, but we could take the approach we took with HP I believe when they messed up some data and temporarily enable `Recruit Type` as a value that can be updated in the `Update Participant Data` API so that the site can send over corrected data.

**Comment by mnataraj92** [comment]
@anthonypetersen that sounds good to me. If @FrogGirl1123 and @brotzmanmj agree I can reach out to Melanie

**Comment by brotzmanmj** [comment]
@mnataraj92 @anthonypetersen sounds like a good plan to me.

**Comment by mnataraj92** [comment]
Reached out to Melanie with this plan
