### ISSUE TITLE
Biospecimen Dashboard - On Collection Data Entry, do not allow the 0050 -0054 series to be entered in for the Biohazard Bags

### ISSUE THREAD

**Issue by wyattks** [episphere/connect#903]
When sites are entering in the Collection ID for the biohazard bags on the Collection Data Entry Screen, do not allow them to enter in 0050 - 0054 for the lsequence number of the ID.  They should aonly be allowed to enter in 0008 or 0009 for the bag IDs.

**Comment by sonyekere** [comment]
Change of SOP, development work to occur some time in April/May

**Comment by JoeArmani** [comment]
Hi @wyattks, I had some time to work through this early. Bag validation needed to be separated from tube validation since the rules are now a bit different (replacement labels 0050-0054 are no longer available for bags).

Would you like changes to any of this error messaging?

(1) Bag ID entry (bags only):
![Image](https://github.com/episphere/connect/assets/93854858/b6a4899a-5091-4b0f-88cf-9fc96519cc86)

(2) Bag ID entry (bags only):
![Image](https://github.com/episphere/connect/assets/93854858/5b92c6c1-ec3d-4a3b-b671-10e70b6773c1)

(3) Collection ID entry (appiles to tubes and bags):
![Image](https://github.com/episphere/connect/assets/93854858/4806286a-8fa3-4a56-a266-1843ffd55745)

(4) Tube entry (tubes only):
![Image](https://github.com/episphere/connect/assets/93854858/7b7707d3-5499-4cb9-a392-daa9871d34df)

**Comment by wyattks** [comment]
I think all the messaging looks good and is detailed on what is needed.

**Comment by JoeArmani** [comment]
Merged to dev, ready to test

**Comment by wyattks** [comment]
Worked in Dev, ready for Stage

**Comment by wyattks** [comment]
Worked in Stage, ready for Prod

**Comment by JoeArmani** [comment]
Closing, this is in production.
