### ISSUE TITLE
Sendgrid Click Tracking (September) 

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#914]
Request turn on functionality for Sendgrid Click tracking.

**Comment by brotzmanmj** [comment]
@jhflorey @HanaShiho Are we ok to turn this on? We have not yet had any issues reported to us by recruits/participants about the magic link since we made that live on Friday.

**Comment by jhflorey** [comment]
I have tried in stage of PWA. The steps as as follows

1. Use Twilio to send the sms that inclue the link https://myconnect-stage.cancer.gov/?clicktracking=twilio
2. Click on the link to open it in my device's browser
3. The next day, go to Google Analytic 4 to find the report as the image below

![image](https://github.com/episphere/connect/assets/24559107/88059956-7ed2-47fe-b38c-365463484dfb)

From the result above, for click tracking for all scenarios such as (Twilio, Sendgrid, etc.) i beleive we can do the same way to monitor in Google Analytics 4. 
We only add the query to the link. The query is whatever It depends on the pattern we want.

Example
- Click tracking for Twilio, we can add query like ?click tracking=twilio 
- Click tracking for Sendgrid we can add query like ?click tracking=sendgrid

**Comment by brotzmanmj** [comment]
@depietrodeanna I don't know much about this. Can you comment? thanks

**Comment by jhflorey** [comment]
It works now on GA4. I have a demo meeting with Hana after her PTO, if team need demo earlier, I can reschedule the meeting. Pls let me know. Thx

**Comment by jhflorey** [comment]
it works on all environments

**Comment by depietrodeanna** [comment]
@jhflorey please set up a short demo with me before Hana is back.

**Comment by brotzmanmj** [comment]
@depietrodeanna yes you are correct, click tracking in Twilio is for SMS and click tracking for SendGrid is for email. About the links, Davin, Hana, and others(?) met with the Twilio rep recently and they said there was Twilio Link Shortening capabilities we could use (they are already part of what we are paying for) in order to customize links and not have them consume a lot of characters in our messages. Is this something you can look into?

**Comment by depietrodeanna** [comment]
@brotzmanmj yes I recall the link shortening conversation; we recorded that Twilio was going to send us some more info about this after we met with them last week..we (at least I) have not received anything but I will check in with our rep! @jhflorey let me know if you have any other details post-our convo with Twilio that I'm not privy to.

**Comment by brotzmanmj** [comment]
Thanks @depietrodeanna and @jhflorey . I defer to you @depietrodeanna as you what links you want to track and what convention you want to use. To function properly does it need to be unique to every message we sent or just in buckets (e.g. survey reminders, newsletters, biospecimen reminder)?

**Comment by mnataraj92** [comment]
Hi all, here is the link to the DD: https://github.com/Analyticsphere/ConnectMasterAndSurveyCombinedDataDictionary/blob/main/MasterSurveyComb_20220317.xlsx

The variables that we already have in the DD for SendGrid tracking are from rows 1903 (CTSG_DeliveredStatus_v1r0) to 1921 (CTSG_UnsubDT_v1r0). All SendGrid variables have a secondary source (column F) of SendGrid and start with "CTSG_".

**Comment by depietrodeanna** [comment]
We have the flexibility to set the click tracking up however we want; it can be as unique or general as we need. To track in individual emails (contact # and email category), we'd need the link to be unique for each specific email. If we just want to track "post verification survey reminders" as a whole (not differentiate between contact attempts, then we'd just use one link (this wouldn't give us much info since I think the most important piece is understanding the effectiveness of each contact attempt. To differentiate between click tracking data among different email categories (biospecimen donation reminders, biosurvey reminders, PROMIS reminders, etc.) we'd need a different link, and within each category a unique link to distinguish reminder 1 from reminder 2, and so forth. So basically every email would need a unique link.

**Comment by jhflorey** [comment]
@depietrodeanna @HanaShiho i've already enabled click tracking in the sendgrid.

**Comment by sonyekere** [comment]
Sendgrid error found using clicking link, functionality has been turned off. DevOps to connect with CBIIT on 'link branding'

**Comment by sonyekere** [comment]
Noted on the punhlist this has been resolved.
