### ISSUE TITLE
Additional Suffixes

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connect#941]
@mnataraj92 to add to the data dictionary change log to add up to suffix VIII for all suffix variables. Will update here when that has been completed and added to the data dictionary.

@sonyekere could you assign this to someone to program?

**Comment by brotzmanmj** [comment]
Hi, Since we are adding more response codes to existing variables but we are not adding a new variable, I'm not sure what the extent of the programming is needed, if any. 

The 'suffix' variable is the indication at the end of someone's name or 'Jr', Sr', II, III, IV, etc. We are extending it add more option up through 'VIII'. The suffix variables is selected from a drop-down list in these places: 
- when someone consents on MyConnect
- when they sign a HIPAA revocation form
- when they sign a data destruction form
- on the SMDB in Participant Details page prior to verification
It displays on each of the forms above plus the HIPAA authorization form when they are viewed or downloaded from MyConnect and from the SMDB.

Is any programming needed to accommodate the additional Suffix categories that will now exist?

**Comment by mnataraj92** [comment]
This has been added to the data dictionary change log. 

@brotzmanmj do we also want 4th, 5th, 6th, 7th, 8th added? Or just IV, V, VI, VII, VIII

**Comment by brotzmanmj** [comment]
Just the roman numerals are fine, thanks

**Comment by sonyekere** [comment]
Davin advised that we may need the suffixes programmed, we'll assign a DevOps team member.

**Comment by mnataraj92** [comment]
Here are the CIDs for the additional suffixes:

 "IV": "611945488",
 "V": "773963342",
 "VI": "911299066",
 "VII": "528373182",
 "VIII": "233284019",

**Comment by brotzmanmj** [comment]
Thanks Madhuri, Nicole mentioned yesterday that we might be best served by labelling them "IV / 4th" or something like that to encompass both ways people might reference these together. Please follow up with Nicole for final determination.

**Comment by bransteitterbr** [comment]
@mnataraj92 How is deprecation of the 2nd and 3rd being handled from a UI perspective?  

1. Should it be removed from the drop down and if we receive 643664527 then have the II selected instead and if the user saves it they would get the new value?  OR
2. Is there a script being planned or ran that will convert the existing data? OR
3. Should it only display the option if previously selected and still allow it to be saved as it originally was?

**Comment by bransteitterbr** [comment]
@brotzmanmj, @Davinkjohnson  For the PDFs do we want the roman numeral `I`, the arabic number `1st`, or the combo like in the dropdown `I, 1st`

**Comment by bransteitterbr** [comment]
For consistency's sake I went with the roman numerals for the printed signatures on the PDF.  If we want to use a different option, it should be a simple change

**Comment by brotzmanmj** [comment]
That sounds fine thanks

**Comment by cunnaneaq** [comment]
Screen shot from the consent signing:
![Screenshot 2024-05-13 at 12 04 44 PM](https://github.com/episphere/connect/assets/83971268/6705724d-339f-4516-a190-156c2b9fdf6b)

Screen shot from the user profile:
![Screenshot 2024-05-13 at 12 09 09 PM](https://github.com/episphere/connect/assets/83971268/e49686ff-ad08-45a9-9f83-b9330c960f78)

**Comment by cunnaneaq** [comment]
Looks good in dev

Re-tested the suffix added during UP and is showing correctly in the SMDB
![Screenshot 2024-05-15 at 9 02 23 AM](https://github.com/episphere/connect/assets/83971268/aa4e2e92-a6ef-4f7e-9a85-1eb2e745f4aa)

**Comment by bransteitterbr** [comment]
Ready for stage

**Comment by cunnaneaq** [comment]
tested same scenarios as above in stage - everything looks good.  Ready for prod

**Comment by sonyekere** [comment]
In Prod
