### ISSUE TITLE
Draft language for To Do list on PWA

### ISSUE THREAD

**Issue by sonyekere** [episphere/connect#948]
Explain to participants that once they start a survey in one language, they have to finish the survey in that language. If they want to start to take the survey in a language different than the current language of the PWA, they need to toggle the language (which will be at the top of the PWA) BEFORE they press "Start" for the module.

**Comment by brotzmanmj** [comment]
@depietrodeanna Do we have the exact language we want to appear (in English and in Spanish)? It seems like this would be best to have in place when we launch Spanish this month.

**Comment by depietrodeanna** [comment]
@brotzmanmj I drafted language and will pass to NORC for translation:

English content:

If you'd like to take this survey in another language, simply click the button at the top of the page to switch to your preferred language before you start. Once you start this survey in one language, you'll need to finish it in that language.

**Comment by brotzmanmj** [comment]
Thanks @depietrodeanna. Will this go at the top of the To Do page on the dashboard? Do we have desired location for it?

**Comment by depietrodeanna** [comment]
I'm not sure yet where the toggle will sit (top right corner of the screen?)

I think it should appear on the top of the To Do list in bold, but I also wonder if it would be worth reiterating elsewhere since the To Do list might get long and people might miss it. We can always adjust but for now just the top of the To Do List would be the one location. It should remain there (not disappear like a yellow bar message).

**Comment by depietrodeanna** [comment]
@bransteitterbr and @jhflorey Spanish content is available here: https://nih.app.box.com/file/1546193790481

**Comment by depietrodeanna** [comment]
@jhflorey I don't see the message displaying in my stage test account?

**Comment by depietrodeanna** [comment]
reviewed again in dev, looks good and ready for stage. @jhflorey

**Comment by depietrodeanna** [comment]
ready for prod
