### ISSUE TITLE
Biospecimen variables not being retained in stub record (May Release)

### ISSUE THREAD

**Issue by robertsamm** [episphere/connect#972]
It was found that there are some biospecimen vars that are not being retained in the stub record that should be. This is because these vars are not nested under CID 173836415.

@mnataraj92 is working to get a full list of the variables that are biospecimen related and not nested under 173836415 so that we can identify which need to be added to the stub record. This includes the baseline biospecimen collection flags below:
1 d_167958071 Base Ur Collected    BioFin_BaseUrineCol_v1r0
2 d_684635302 Base MW Collected    BioFin_BaseMouthCol_v1r0
3 d_878865966 Base Blood Collected BioFin_BaseBloodCol_v1r0

Once identified, we will need to add these additional variables to the stub record.

@sonyekere can you see where this fits in priorities?

**Comment by robertsamm** [comment]
See related issue #937

**Comment by sonyekere** [comment]
Hi @robertsamm I say that we prioritize this as much as we can . Timing is key here since we only have Thursday and Friday before stage. 

 @jhflorey As mentioned above, there are a list of the variables that are biospecimen related and not nested under 173836415. Once Madhuri and team can provide the additional variables, could you update your code to retain those variables? Data destruction is a big lift so I appreciate your work here. I believe you only have sendgrid clean ups and will be prioritizing as much as you can below.

@jhflorey To ensure we are on the same page. I believe that there are a total of **5 GitHub issues** open pertaining to Data Destruction

1. #937 - **Issue needs fixing** 
-The SSN survey status on the SMDB is not pointing to the correct flag
- Issue where the participant summary page of SMDB is showing the wrong status for SSN and biospecimen samples collected ( tied to the below issues as well) 

2. #962 - Looks fixed, **Ops will need to provide formal update of dev status in the issue** so this can be marked ready for stage
- Any issue that needs to be fixed is tied to this new issue 972 ( Update to the sub record variables) 

3. #959 - Looks Fixed. **Pending testing plan** from Ops

4. #972 - The new issue mentioned above. @jhflorey You are **pending the biospecimen variable listing** that will need to be retained. Again, once you get that comprehensive list from Ops please try to update your code. 

5. #973 - New issue created today to restore Prod participants biospecimen data that was destroyed and not retained. @jhflorey you are **pending that list of participants/Connect Ids**. Madurai and Amelia will connect to work on getting that list together of participants whose data was destroyed.

@robertsamm I think I have it all down in order of priority. Really all of it is important and depends on timing here. I hope this helps.

**Comment by robertsamm** [comment]
Hello @kmazzilli and @cunnaneaq, we plan on trying to get this fix in dev and tested with the dev cycle this week if we can. I will be OOO tomorrow so just a heads up we may pull you in to help test this tomorrow. There are some biospecimen variables in the participants table that weren't being retained in the stub record after data destruction as they aren't nested under one of the main biospec CIDs. This includes the flags for blood, urine, mouthwash collected =yes or no.

**Comment by robertsamm** [comment]
Update: this fix will be getting moved to the May release. In the meantime, we plan to stop running the data destruction automation in prod until this is fixed. 

@jhflorey can you turn off data destruction in prod?
@mnataraj92 has the list of about ~17 CIDs related to Biospecimens that will need to be added to the stub record in the May release and will provide them soon.

**Comment by mnataraj92** [comment]
@jhflorey  Here is the list of the 17 biospecimen variables to be added to the stub record
[Participants Table Biospecimen Vars.xlsx](https://github.com/episphere/connect/files/15030905/Participants.Table.Biospecimen.Vars.xlsx)

**Comment by jhflorey** [comment]
> Update: this fix will be getting moved to the May release. In the meantime, we plan to stop running the data destruction automation in prod until this is fixed.
> 
> @jhflorey can you turn off data destruction in prod? @mnataraj92 has the list of about ~17 CIDs related to Biospecimens that will need to be added to the stub record in the May release and will provide them soon.

I do not have permission in prod. Let me ask Tony.

**Comment by jhflorey** [comment]
> > Update: this fix will be getting moved to the May release. In the meantime, we plan to stop running the data destruction automation in prod until this is fixed.
> > @jhflorey can you turn off data destruction in prod? @mnataraj92 has the list of about ~17 CIDs related to Biospecimens that will need to be added to the stub record in the May release and will provide them soon.
> 
> I do not have permission in prod. Let me ask Tony.

@robertsamm just paused

**Comment by jhflorey** [comment]
@mnataraj92 @robertsamm the code for adding biospecimen variables have been already merged into dev. You can test in dev now.

**Comment by robertsamm** [comment]
@sonyekere @Davinkjohnson is this part of the April or May release for testing? A decision was made last week to move this to May, but I was OOO on Friday and may have missed updates. I don't know if there is enough time to test this in dev before stage push today.

**Comment by sonyekere** [comment]
Hi @robertsamm No worries!  Just saw confirmation that this was indeed projected for the May release. April testing will not be needed.

**Comment by mnataraj92** [comment]
Tested in dev, ready for stage

**Comment by sonyekere** [comment]
In Prod
